jobaddservice/oauth/models.py
from flask import request
from datetime import datetime, timedelta
from werkzeug.security import gen_salt
from ..database import db
import bcrypt


class User(db.Model):
    """The OAuth2 provider and general application user."""

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(40), unique=True)
    hashpw = db.Column(db.String(80))

    @staticmethod
    def find_with_password(username, password, *args, **kwargs):
        """Finds a user given his username and plain password."""
        user = User.query.filter_by(username=username).first()
        encodedpw = password.encode('utf-8')
        userhash = user.hashpw.encode('utf-8')
        return User.query.filter(
            User.username == username,
            User.hashpw == bcrypt.hashpw(encodedpw, userhash)
        ).first()

    @staticmethod
    def save(username, password):
        """Finds a user given his username and plain password."""
        salt = bcrypt.gensalt()
        hash = bcrypt.hashpw(password.encode('utf-8'), salt)
        user = User(username=username, hashpw=hash)
        db.session.add(user)
        db.session.commit()

    @staticmethod
    def all():
        """Returns all users."""
        return User.query.all()

    @staticmethod
    def get_authorized():
        """Returns the currently authorized user."""
        access_token = request.oauth.headers.get('Authorization').split(' ')[1]
        token = Token.find(access_token)
        return token.user


class Client(db.Model):
    """The OAuth2 application client."""

    client_id = db.Column(db.String(40), primary_key=True)
    client_type = db.Column(db.String(40))

    @property
    def allowed_grant_types(self):
        """Default client grant types."""
        return ['password']

    @property
    def default_scopes(self):
        """Default client scopes."""
        return []

    @staticmethod
    def find(id):
        """Finds a client by its id."""
        return Client.query.filter_by(client_id=id).first()

    @staticmethod
    def generate():
        """Generates a new public client."""
        client = Client(client_id=gen_salt(40), client_type='public')
        db.session.add(client)
        db.session.commit()

    @staticmethod
    def all():
        """Returns all clients."""
        return Client.query.all()

    def default_redirect_uri():  # pragma: no cover
        """Returns the default redirect URI."""
        return ''


class Token(db.Model):
    """The OAuth2 client token."""

    id = db.Column(db.Integer, primary_key=True)
    client_id = db.Column(
        db.String(40), db.ForeignKey('client.client_id'), nullable=False)
    client = db.relationship('Client')
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User')
    token_type = db.Column(db.String(40))
    access_token = db.Column(db.String(255), unique=True)
    refresh_token = db.Column(db.String(255), unique=True)
    expires = db.Column(db.DateTime)
    scopes = ['']

    @staticmethod
    def all():
        """Returns all tokens."""
        return Token.query.all()

    @staticmethod
    def find(access_token):
        """Finds an access token given its identifier."""
        return Token.query.filter_by(access_token=access_token).first()

    @staticmethod
    def save(token, request, *args, **kwargs):
        """Creates a new token per client and user."""
        toks = Token.query.filter_by(
            client_id=request.client.client_id, user_id=request.user.id)

        # Make sure there is only one token for every client and user.
        [db.session.delete(t) for t in toks]

        expires_in = token.pop('expires_in')
        expires = datetime.utcnow() + timedelta(seconds=expires_in)

        tok = Token(
            access_token=token['access_token'],
            refresh_token=token['refresh_token'],
            token_type=token['token_type'],
            expires=expires,
            client_id=request.client.client_id,
            user_id=request.user.id,
        )

        db.session.add(tok)
        db.session.commit()

jobaddservice/oauth/__init__.py
from flask import Blueprint
from flask_oauthlib.provider import OAuth2Provider


oauth = Blueprint(
    'oauth', __name__, template_folder='templates', static_folder='static')
"""OAuth2 provider blueprint."""

provider = OAuth2Provider()
"""OAuth2 provider."""

from . import views  # nopep8

jobaddservice/oauth/views.py
from . import oauth
from flask import render_template, request
from models import Client, User, Token
from . import provider


@oauth.route('/token', methods=['POST'])
@provider.token_handler
def access_token(*args, **kwargs):
    """Creates a token given a user name, password and client id."""
    return None


@oauth.route('/check', methods=['GET'])
@provider.require_oauth()
def check():
    """Shows who the authorized user is."""
    access_token = request.oauth.headers.get('Authorization').split(' ')[1]
    token = Token.find(access_token)
    return 'Authorized as {}'.format(token.user.username)


@oauth.route('/', methods=['GET', 'POST'])
def management():
    """Provides a quick management screen for users, clients and tokens."""
    if request.method == 'POST' and request.form['submit'] == 'Add User':
        # Create a new user if the 'Add User' form has been sent.
        User.save(request.form['username'], request.form['password'])
    if request.method == 'POST' and request.form['submit'] == 'Add Client':
        # Create a new client if the 'Add Client' form has been sent.
        Client.generate()
    # Show the management page.
    return render_template(
        'management.html',
        users=User.all(),
        clients=Client.all(),
        tokens=Token.all()
    )

jobaddservice/oauth/templates/management.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="OAuth2 Management">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>OAuth2 Management</title>
    <link rel="shortcut icon" href="{{ url_for('oauth.static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('oauth.static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.teal-red.min.css">
    <link rel="stylesheet" href="{{ url_for('oauth.static', filename='style.css') }}">
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-color--grey-100">
      <main class="mdl-layout__content">
        <!-- Tabbed layout. -->
        <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
          <div class="mdl-tabs__tab-bar">
            <a href="#users" class="mdl-tabs__tab is-active">Users ({{ users|length }})</a>
            <a href="#clients" class="mdl-tabs__tab">Clients ({{ clients|length }})</a>
            <a href="#tokens" class="mdl-tabs__tab">Tokens ({{ tokens|length }})</a>
          </div>
          <!-- User tab. -->
          <div class="mdl-tabs__panel is-active" id="users">
            <div class="mdl-grid">
              <div class="mdl-cell mdl-cell--2-col"></div>
              <div class="mdl-cell mdl-cell--8-col">
                <form method="post" action="{{ url_for('oauth.management') }}">
                  <div class="mdl-textfield mdl-js-textfield">
                    <input class="mdl-textfield__input" type="text" id="username" name="username" required>
                    <label class="mdl-textfield__label" for="username">Username</label>
                  </div>
                  <div class="mdl-textfield mdl-js-textfield">
                    <input class="mdl-textfield__input" type="password" id="password" name="password" required>
                    <label class="mdl-textfield__label" for="password">Password</label>
                  </div>
                  <br/>
                  <input type="submit" name='submit' value='Add User'
                  class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
                </form>
                <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
                  <thead>
                    <tr>
                      <th class="mdl-data-table__cell--non-numeric">ID</th>
                      <th class="mdl-data-table__cell--non-numeric">Username</th>
                      <th class="mdl-data-table__cell--non-numeric">Password Hash</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for user in users %}
                    <tr>
                      <td class="mdl-data-table__cell--non-numeric">{{ user.id }}</td>
                      <td class="mdl-data-table__cell--non-numeric">{{ user.username }}</td>
                      <td class="mdl-data-table__cell--non-numeric">{{ user.hashpw }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!-- Client tab. -->
          <div class="mdl-tabs__panel" id="clients">
            <div class="mdl-grid">
              <div class="mdl-cell mdl-cell--2-col"></div>
              <div class="mdl-cell mdl-cell--8-col">
                <form method="post" action="{{ url_for('oauth.management') }}">
                  <input type="submit" name='submit' value='Add Client'
                  class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
                </form>
                <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
                  <thead>
                    <tr>
                      <th class="mdl-data-table__cell--non-numeric">ID</th>
                      <th class="mdl-data-table__cell--non-numeric">Type</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for client in clients %}
                    <tr>
                      <td class="mdl-data-table__cell--non-numeric">{{ client.client_id }}</td>
                      <td class="mdl-data-table__cell--non-numeric">{{ client.client_type }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!-- Token tab. -->
          <div class="mdl-tabs__panel" id="tokens">
            <div class="mdl-grid">
              <div class="mdl-cell mdl-cell--2-col"></div>
              <div class="mdl-cell mdl-cell--8-col">
                <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
                  <thead>
                    <tr>
                      <th class="mdl-data-table__cell--non-numeric">ID</th>
                      <th class="mdl-data-table__cell--non-numeric">User ID</th>
                      <th class="mdl-data-table__cell--non-numeric">Client ID</th>
                      <th class="mdl-data-table__cell--non-numeric">Expires</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for token in tokens %}
                    <tr onclick="alert('{{ token.access_token }}')">
                      <td class="mdl-data-table__cell--non-numeric">{{ token.id }}</td>
                      <td class="mdl-data-table__cell--non-numeric">{{ token.user_id }}</td>
                      <td class="mdl-data-table__cell--non-numeric">{{ token.client_id }}</td>
                      <td class="mdl-data-table__cell--non-numeric">{{ token.expires }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
    <!-- Footer scripts. -->
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
</html>